base_url: hass.url.com
lat: 00.00000
long: 00.00000
mqtt_username: mqttusr
mqtt_password: mqttpwd
ns_password: ab12cd34ef56gh78ij90kl
synology_url: https://url.to.nas
synology_login: synologyusr
synology_pass: synologypwd
postnluser: postnlusr
postnlpwd: postnlpwd
htmlkey: AAAAAAAAAAAAAAAAAAAAAAA:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_00000000000000000000000000000
htmlsenderid: 000000000000
darksky: aaaaaaaaaaaaa00000000000000000
hassconf: https://hass.config.url
esphome: https://esphome.config.url
mariadb: mysql://hass:hass@192.0.0.0:0000/hassiodb
influxdburl: https://influx.config.url
influxdbpass: influxpwd
travissensortoken: aaaaaaaaaaaaaaaaaaaa000000000000000000